spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true

  cloud:
    gcp:
      # "location" 설정 삭제 혹은 무시 (우리는 GOOGLE_APPLICATION_CREDENTIALS로 인증)
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS}

ai:
  gemini:
    base-host: generativelanguage.googleapis.com
    key: ${AI_GEMINI_API_KEY}

kakao:
  auth:
    client: ${KAKAO_CLIENT_ID}
    redirect: http://localhost:8080/auth/login/kakao

logging:
  level:
    org.springframework.web: DEBUG
