spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB
  cloud:
    gcp:
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          ssl: false
          starttls:
            enable: true
            required: true

ai:
  gemini:
    base-host: generativelanguage.googleapis.com
    key: ${AI_GEMINI_API_KEY}
    location:
      chat: ${AI_GEMINI_CHAT_PROMPT_LOCATION}
      summary: ${AI_GEMINI_SUMMARY_PROMPT_LOCATION}

kakao:
  auth:
    client: ${KAKAO_CLIENT_ID}
    redirect: http://localhost:8080/auth/login/kakao

logging:
  level:
    org.springframework.web: DEBUG